[package]
name = "vm116"
version = "0.0.1"
license = "GPLv3"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com"]
keywords = ["usb", "dmx", "velleman", "hardware"]

[dependencies]
gtk = "*"
libusb = "*"
